name = "Acropolis"
author = "GBLodb, Lubang_Official, IsaacTadokoro"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2464d7e47f2a7d3f8e84f03f8d474b307e6eea3fe3839e605d43cdad0ab1b6d2"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
